###
Post http://localhost:8000/api/v1/users/
Content-Type: application/json

{"firstName": "stam",
"lastName": "stam",
"email":"stam@gmail.com",
"password": "123456",
"address": "stamaddress",
"latAndLong": "123, 456",
"phone": "123456"}

###
Post http://localhost:8000/api/v1/users/login
Content-Type: application/json

{"email":"stam@gmail.com",
"password": "123456"}

###
GET http://localhost:8000/api/v1/cardTypes
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTQ5Yjg5MzgwNzc4NzJkNGRiZGY4MyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTQ5NTQ5MTgsImV4cCI6MTY1NTA0MTMxOH0.J6FmPbHTYvrEbhVYJ5emVmf37hl2dgF1CCTU_5MyC6Q

###

POST  http://localhost:8000/api/v1/userClicks/
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTQ5Yjg5MzgwNzc4NzJkNGRiZGY4MyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTQ5NTQ5MTgsImV4cCI6MTY1NTA0MTMxOH0.J6FmPbHTYvrEbhVYJ5emVmf37hl2dgF1CCTU_5MyC6Q
Content-Type: application/json

{"cardTypeId":"62532859427c06ccbf55d31e",
"userId" : "62a49b8938077872d4dbdf83",
"owner": "6256a44c1e29497041970877",
"expirationDate": "1650724691030",
 "price": 100,
 "value": 120,
 "cardNumber": "12345",
 "isForSale": true
}