###
Post http://localhost:8001/api/v1/users/
Content-Type: application/json

{"firstName": "stam",
"lastName": "stam",
"email":"shirr@gmail.com",
"password": "123456",
"address": "stamaddress",
"latAndLong": "123, 456",
"phone": "123456"}

###
Post http://localhost:8001/api/v1/users/login
Content-Type: application/json

{"email":"stam@gmail.com",
"password": "123456"}

###
GET http://localhost:8001/api/v1/cards
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWVhZDZlNzE5YWU2NjJlMzM2ZjY0YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTA3MjM1NDQsImV4cCI6MTY1MDgwOTk0NH0.5KAocu6uECIBSOeVFB6JCU90OwVYScQfpgvs_RfFTgo

###

PUT http://localhost:8001/api/v1/users/addOne/625ead6e719ae662e336f64c
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWVhZDZlNzE5YWU2NjJlMzM2ZjY0YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTM5Mzk4MzYsImV4cCI6MTY1NDAyNjIzNn0.lT_c1yl7-MZaMRcqyZLQreb5qmhh4nZTYTEewZVVeJQ
Content-Type: application/json

{"category": "Health"}