###
Post http://localhost:8001/api/v1/users/
Content-Type: application/json

{"firstName": "stam",
"lastName": "stam",
"email":"stam@gmail.com",
"password": "123456",
"address": "stamaddress",
"latAndLong": "123, 456",
"phone": "123456"}

###
Post http://localhost:8001/api/v1/users/login
Content-Type: application/json

{"email":"stam@gmail.com",
"password": "123456"}

###
GET http://localhost:8001/api/v1/cards
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWVhZDZlNzE5YWU2NjJlMzM2ZjY0YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTA3MjM1NDQsImV4cCI6MTY1MDgwOTk0NH0.5KAocu6uECIBSOeVFB6JCU90OwVYScQfpgvs_RfFTgo

###

POST  http://localhost:8001/api/v1/cards/
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWVhZDZlNzE5YWU2NjJlMzM2ZjY0YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTA3MjI1MTYsImV4cCI6MTY1MDgwODkxNn0.81jVCc3YKAIbsTGPWFoD7Z_7sqbQfJJKGOCxCb-JSZs
Content-Type: application/json

{"cardType":"62532859427c06ccbf55d31e",
"owner": "6256a44c1e29497041970877",
"expirationDate": "1650724691030",
 "price": 100,
 "value": 120,
 "cardNumber": "12345",
 "isForSale": true
}